# Generated by Django 6.0 on 2025-12-30 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='dark', max_length=10)),
                ('font', models.CharField(choices=[('system', 'Sistema'), ('montserrat', 'Montserrat'), ('roboto', 'Roboto'), ('lora', 'Lora (serif)')], default='system', max_length=20)),
                ('slider_background', models.ImageField(blank=True, null=True, upload_to='slider_backgrounds/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(blank=True, default=False)),
                ('pre_loaded', models.BooleanField(blank=True, default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.event')),
            ],
        ),
    ]
