# Generated by Django 6.0 on 2025-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pre_loaded',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
