# Generated by Django 6.0 on 2026-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_square_screen',
            field=models.BooleanField(default=False, help_text='Marca esta opción si la pantalla del evento es cuadrada.'),
        ),
    ]
