# Generated by Django 6.0 on 2025-12-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_photo_pre_loaded_alter_photo_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
